### ISSUE TITLE
Lookup menu glitch

### ISSUE THREAD

**Issue by iampaulc** [gleemcbean/hopmytrack#5]
**Describe the bug**
Going back to the menu after ctrl z in lookup tab just continue the task in the home page

**To Reproduce**
1. Go to 'HMT main menu'
2. Click on 'lookup'
3. Fill the first question 
4. Do CTRL Z to go back to the menu
5. Reenter into lookup

**Expected behavior**
Should restart in a new page

**Screenshots**
![image](https://github.com/user-attachments/assets/96e0f85a-502a-40f6-b1e4-7bcd35a88af8)

**Desktop (please complete the following information):**
 - OS: W11
 - Version 0.1.23

**Comment by gastonchenet** [comment]
👋 Hello @iampaulc 

Thank you for submitting this issue, this bug is now fixed in the last commit and will be fixed in the next release.

Have a nice day !
